# Generated by Django 4.0 on 2022-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_collection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
