# Generated by Django 4.0 on 2022-08-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_source_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
