# Generated by Django 4.0 on 2022-08-01 17:50

import backend.sources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_alter_feed_admin_rss_enabled_alter_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='service',
            field=models.CharField(choices=[(backend.sources.models.Source.SourcePlatforms['ONLINE_NEWS'], 'online_news'), (backend.sources.models.Source.SourcePlatforms['YOUTUBE'], 'youtube')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url_search_string',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
