# Generated by Django 4.0 on 2022-08-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_alter_source_homepage_alter_source_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='homepage',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
