# Generated by Django 4.0 on 2022-08-02 13:21

import backend.sources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_alter_source_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='media_type',
            field=models.CharField(choices=[(backend.sources.models.MediaTypes['AUDIO_BROADCAST'], 'audio_broadcast'), (backend.sources.models.MediaTypes['DIGITAL_NATIVE'], 'digital_native'), (backend.sources.models.MediaTypes['PRINT_NATIVE'], 'print_native'), (backend.sources.models.MediaTypes['OTHER'], 'other'), (backend.sources.models.MediaTypes['VIDEO_BROADCAST'], 'video_broadcast')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='primary_language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='pub_country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='pub_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
