# Generated by Django 4.0 on 2022-08-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_source_media_type_source_primary_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='pub_country',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
