# Generated by Django 4.0 on 2022-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_alter_source_pub_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='primary_language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
