# Generated by Django 4.0 on 2022-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_alter_source_primary_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='first_story',
            field=models.DateTimeField(null=True),
        ),
    ]
