# Generated by Django 4.0.7 on 2022-11-09 19:52

import backend.sources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_collection_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='service',
        ),
        migrations.AddField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[(backend.sources.models.Source.SourcePlatforms['ONLINE_NEWS'], 'online_news'), (backend.sources.models.Source.SourcePlatforms['YOUTUBE'], 'youtube'), (backend.sources.models.Source.SourcePlatforms['REDDIT'], 'reddit')], default='online_news', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='platform',
            field=models.CharField(choices=[(backend.sources.models.Collection.CollectionPlatforms['ONLINE_NEWS'], 'online_news'), (backend.sources.models.Collection.CollectionPlatforms['REDDIT'], 'reddit'), (backend.sources.models.Collection.CollectionPlatforms['YOUTUBE'], 'youtube')], default='online_news', max_length=100, null=True),
        ),
    ]
