# Generated by Django 4.1.3 on 2022-12-07 20:34

import backend.sources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0016_remove_source_service_source_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='platform',
            field=models.CharField(choices=[(backend.sources.models.Collection.CollectionPlatforms['ONLINE_NEWS'], 'online_news'), (backend.sources.models.Collection.CollectionPlatforms['REDDIT'], 'reddit'), (backend.sources.models.Collection.CollectionPlatforms['TWITTER'], 'twitter'), (backend.sources.models.Collection.CollectionPlatforms['YOUTUBE'], 'youtube')], default='online_news', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[(backend.sources.models.Source.SourcePlatforms['ONLINE_NEWS'], 'online_news'), (backend.sources.models.Source.SourcePlatforms['YOUTUBE'], 'youtube'), (backend.sources.models.Source.SourcePlatforms['TWITTER'], 'twitter'), (backend.sources.models.Source.SourcePlatforms['REDDIT'], 'reddit')], default='online_news', max_length=100, null=True),
        ),
    ]
