# Generated by Django 4.1.3 on 2022-12-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0019_alter_source_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('name', 'platform', 'url_search_string'),
                                               name='unique names within platform'),
        ),
    ]
