# Generated by Django 4.1.6 on 2023-02-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0021_collection_featured_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='collections',
            field=models.ManyToManyField(blank=True, to='sources.collection'),
        ),
    ]
