# Generated by Django 4.1.6 on 2023-02-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_alter_collection_featured_alter_collection_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured',
        ),
    ]
