# Generated by Django 4.1.6 on 2023-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0023_remove_collection_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
