# Generated by Django 4.1.6 on 2023-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0023_source_alerted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='alerted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
