# Generated by Django 4.1.13 on 2024-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0023_source_alerted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="alerted",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
