# Generated by Django 4.1.13 on 2024-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0024_alter_source_alerted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="featured",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
