# Generated by Django 4.1.6 on 2024-10-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_collection_static'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='static',
            new_name='managed',
        ),
    ]
