# Generated by Django 4.1.6 on 2023-03-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_alter_source_collections_alter_source_homepage'),
        ('sources', '0024_collection_featured'),
    ]

    operations = [
    ]
