# Generated by Django 4.1.6 on 2024-11-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0025_rename_static_collection_managed"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="last_rescraped",
            field=models.DateTimeField(null=True),
        ),
    ]
