# Generated by Django 4.1.13 on 2024-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0025_alter_collection_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="public",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
