# Generated by Django 4.1.6 on 2024-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0026_source_last_rescraped"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="last_rescraped_msg",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
