# Generated by Django 4.1.13 on 2024-10-31 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0025_rename_static_collection_managed"),
        ("sources", "0026_alter_collection_public"),
    ]

    operations = []
