# Generated by Django 4.1.13 on 2025-03-04 20:41
# with help from https://medium.com/@nandagopal05/django-full-text-search-with-postgresql-f063aaf34e35
# code: https://github.com/NandaGopal56/Django-full-text-search/blob/main/books/migrations/0003_book_search_vector_trigger.py

from django.db import migrations
from django.contrib.postgres.search import SearchVector

def compute_search_vector(apps, schema_editor):
    Source = apps.get_model("sources", "Source")
    Source.objects.update(search_vector=SearchVector("name", "label"))

class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0028_source_name_label_ginindex'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
              CREATE TRIGGER search_vector_trigger
              BEFORE INSERT OR UPDATE OF name, label, search_vector
              ON sources_source
              FOR EACH ROW EXECUTE PROCEDURE
              tsvector_update_trigger(
                search_vector, 'pg_catalog.english', name, label
              );
              UPDATE sources_source SET search_vector = NULL;
            ''',

            reverse_sql = '''
              DROP TRIGGER IF EXISTS search_vector_trigger
              ON sources_source;
            '''
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
