# Generated by Django 4.1.6 on 2025-05-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0029_create_vector_search_trigger"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="source",
            new_name="search_vector_gin_index",
            old_name="sources_source_name_label_gin",
        ),
    ]
