# Generated by Django 4.1.6 on 2025-05-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "sources",
            "0030_rename_sources_source_name_label_gin_search_vector_gin_index",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternativeDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sources.source"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="alternativedomain",
            index=models.Index(fields=["domain"], name="domain"),
        ),
    ]
