# Generated by Django 4.1.6 on 2025-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0031_alternativedomain_alternativedomain_domain"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alternativedomain",
            index=models.Index(fields=["source"], name="source"),
        ),
        migrations.AddConstraint(
            model_name="alternativedomain",
            constraint=models.UniqueConstraint(
                fields=("source", "domain"), name="unique_source_domain"
            ),
        ),
    ]
