# Generated by Django 4.1.6 on 2025-12-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0032_alternativedomain_source_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"permissions": (("edit_collection", "Edit collection"),)},
        ),
    ]
