# Generated by Django 4.1.13 on 2026-01-23 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0033_alter_collection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('user_email', models.CharField(blank=True, max_length=254)),
                ('action_type', models.CharField(max_length=50)),
                ('object_model', models.CharField(choices=[('Source', 'Source'), ('Collection', 'Collection'), ('Feed', 'Feed'), ('AlternativeDomain', 'Alternative Domain')], max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=5000)),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='sources.actionhistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actionhistory',
            index=models.Index(fields=['object_model', 'object_id'], name='sources_act_object__4688a7_idx'),
        ),
        migrations.AddIndex(
            model_name='actionhistory',
            index=models.Index(fields=['user', '-created_at'], name='sources_act_user_id_5e7c02_idx'),
        ),
        migrations.AddIndex(
            model_name='actionhistory',
            index=models.Index(fields=['action_type', '-created_at'], name='sources_act_action__041dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='actionhistory',
            index=models.Index(fields=['parent_event'], name='sources_act_parent__ca82e5_idx'),
        ),
    ]
