# Generated by Django 4.1.13 on 2026-01-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0034_actionhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='first_story',
            new_name='last_story',
        ),
    ]
