# Generated by Django 4.1.13 on 2026-01-27 20:33
from django.db import migrations


class Migration(migrations.Migration):
    """
    NULL out Source.last_story and Source.stories_per_week.
    This should have been part of
    0035_rename_first_story_source_last_story.

    This, in combination with "manage.py source-tweak-stories-per-week"
    ensure that:
    * Any source with no searchable stories (2008-current) will have NULL
      last_stories (formerly first_stories, which contained pre-2008 dates),
      and stories_per_week.
    * Sources with searchable stories will never have a NULL stories_per_week.
    """
    dependencies = [
        ('sources', '0035_rename_first_story_source_last_story'),
    ]

    operations = [
        migrations.RunSQL(
            sql='UPDATE sources_source SET last_story = NULL, stories_per_week = NULL;'
        )
        # no reverse_sql argument (irrerversible)
    ]
