# Generated by Django 4.1.13 on 2026-02-04 21:45

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0036_null_last_and_weekly'),
    ]

    operations = [
        # enable pg_trgm extension.
        # this is alone so that the next migration can be reversible!
        TrigramExtension(),
    ]
