# Generated by Django 4.1.13 on 2026-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0038_source_name_label_trigram_gin_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='stories_total',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='stories_date_past',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='stories_date_future',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='stories_date_empty',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
