# Generated by Django 4.1.13 on 2026-03-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0040_collection_featured_rank'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['monitored'], name='collection_monitored'),
        ),
    ]
