# Generated by Django 4.1.13 on 2026-03-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0041_collection_collection_monitored'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataUpdateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('updated', models.IntegerField()),
                ('run_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
