# Generated by Django 4.1.13 on 2026-06-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0042_metadataupdatetask'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alternativedomain',
            name='unique_source_domain',
        ),
        migrations.AddField(
            model_name='alternativedomain',
            name='url_search_string',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddConstraint(
            model_name='alternativedomain',
            constraint=models.UniqueConstraint(fields=('domain', 'url_search_string'), name='unique_domain_uss'),
        ),
    ]
