# Generated by Django 4.1.13 on 2026-08-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0043_alternative_domain_add_url_search_string'),
    ]

    operations = [
        # Django >= 6.0 no longer emits DROP COLUMN ... CASCADE, so the
        # trigger created in 0029 must be dropped explicitly before the
        # column it depends on goes away.
        migrations.RunSQL(
            sql='DROP TRIGGER IF EXISTS search_vector_trigger ON sources_source;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveIndex(
            model_name='source',
            name='search_vector_gin_index',
        ),
        migrations.RemoveField(
            model_name='source',
            name='search_vector',
        ),
    ]
