# Generated by Django 4.1.13 on 2026-08-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0043_alternative_domain_add_url_search_string'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='source',
            name='search_vector_gin_index',
        ),
        migrations.RemoveField(
            model_name='source',
            name='search_vector',
        ),
    ]
