# Generated by Django 4.0 on 2022-08-01 16:57

from backend.directory.models import Source
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_alter_collection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url_search_string', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=255)),
                ('homepage', models.CharField(max_length=1000)),
                ('notes', models.TextField()),
                ('service', models.CharField(choices=[(Source.SourcePlatforms['ONLINE_NEWS'], 'online_news'), (Source.SourcePlatforms['YOUTUBE'], 'youtube')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('stories_per_week', models.IntegerField(default=0, null=True)),
                ('collections', models.ManyToManyField(to='directory.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('admin_rss_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.source')),
            ],
        ),
    ]
