# Generated by Django 4.0 on 2022-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_feed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='admin_rss_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
