# Generated by Django 4.0 on 2022-08-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_alter_source_notes_alter_source_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='homepage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
