# Generated by Django 4.1.3 on 2022-12-15 19:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_alter_source_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
