# Generated by Django 4.1.6 on 2023-02-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_collection_featured_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='collections',
            field=models.ManyToManyField(blank=True, to='directory.collection'),
        ),
        migrations.AlterField(
            model_name='source',
            name='homepage',
            field=models.CharField(max_length=4000),
        ),
    ]
