# Generated by Django 4.1.6 on 2023-06-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_alter_source_collections_alter_source_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='alerted',
            field=models.BooleanField(default=False),
        ),
    ]
