# Generated by Django 4.1.3 on 2023-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0023_source_alerted"),
    ]

    operations = [
        # migrations.AddIndex(
        #     model_name="collection",
        #     index=models.Index(fields=["platform"], name="collection platform"),
        # ),
        # migrations.AddIndex(
        #     model_name="source",
        #     index=models.Index(fields=["platform"], name="source platform"),
        # ),
        # migrations.AddConstraint(
        #     model_name="source",
        #     constraint=models.UniqueConstraint(
        #         fields=("name", "platform", "url_search_string"),
        #         name="unique names within platform",
        #     ),
        # ),
    ]
