# Generated by Django 4.1.3 on 2022-11-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='was_imported',
            field=models.BooleanField(default=False),
        ),
    ]
