# Generated by Django 4.1.3 on 2022-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_was_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imported_password_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
