# Generated by Django 4.1.3 on 2022-11-29 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile_quota_mediacloud_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='QuotaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.TextField()),
                ('week', models.DateField()),
                ('hits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='quotahistory',
            index=models.Index(fields=['user_id', 'provider', 'week'], name='user_quota_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='quotahistory',
            index=models.Index(fields=['provider'], name='user_quota_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='quotahistory',
            index=models.Index(fields=['week'], name='user_quota_week_idx'),
        ),
    ]
