# Generated by Django 4.1.3 on 2022-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
