# Generated by Django 4.1.3 on 2022-11-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_created_at_profile_modified_at_quotahistory_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quotahistory',
            constraint=models.UniqueConstraint(fields=('user_id', 'provider', 'week'), name='unique user_provider_week'),
        ),
    ]
