# Generated by Django 4.1.3 on 2022-12-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_registered'),
        ('users', '0006_quotahistory_unique user_provider_week'),
    ]

    operations = [
    ]
