# Generated by Django 4.1.3 on 2022-12-01 14:49

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Profile = apps.get_model("users", "Profile")
    db_alias = schema_editor.connection.alias
    Profile.objects.using(db_alias).filter(user__is_staff=False).update(quota_twitter=10)


def reverse_func(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    db_alias = schema_editor.connection.alias
    Profile.objects.using(db_alias).filter(user__is_staff=False).update(quota_twitter=10000)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_quotahistory_unique user_provider_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quota_twitter',
            field=models.IntegerField(default=10),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
