# Generated by Django 4.1.3 on 2022-12-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_quota_twitter'),
        ('users', '0007_merge_20221201_1431'),
    ]

    operations = [
    ]
