# Generated by Django 4.1.3 on 2022-12-06 20:17
# @see https://stackoverflow.com/questions/32723601/how-do-you-use-the-migration-framework-to-add-django-rest-framework-authenticati

import binascii
import os

from django.db import migrations


# Copied from rest_framework/authtoken/models.py.
def generate_key():
    return binascii.hexlify(os.urandom(20)).decode()


def create_tokens(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Token = apps.get_model('authtoken', 'Token')
    for user in User.objects.filter(auth_token__isnull=True):
        token, _ = Token.objects.get_or_create(user=user, key=generate_key())


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20221202_0238'),
    ]

    operations = [
        migrations.RunPython(create_tokens),
    ]