# Generated by Django 4.1.3 on 2022-12-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_generate_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registered',
        ),
    ]
