# Generated by Django 4.1.3 on 2023-01-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quota_mediacloud_legacy',
        ),
    ]
