# Generated by Django 4.1.3 on 2023-07-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0012_profile_quota_mediacloud_legacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSecrets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_name",
                    models.CharField(
                        choices=[
                            ("twitter-token", "Twitter Token"),
                            ("youtube-token", "Youtube Token"),
                        ],
                        max_length=150,
                    ),
                ),
                ("api_key", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
