# Generated by Django 4.1.6 on 2023-11-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_quota_mediacloud_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quota_mediacloud',
            field=models.IntegerField(default=100000),
        ),
    ]
