# Generated by Django 4.1.6 on 2024-11-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_profile_quota_mediacloud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="quota_mediacloud",
            field=models.IntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="quota_mediacloud_legacy",
            field=models.IntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="quota_reddit_pushshift",
            field=models.IntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="quota_wayback_machine",
            field=models.IntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="quota_youtube",
            field=models.IntegerField(default=4000),
        ),
    ]
