# Generated by Django 4.1.3 on 2023-07-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_usersecrets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersecrets", old_name="api_name", new_name="key",
        ),
        migrations.RenameField(
            model_name="usersecrets", old_name="user", new_name="user_id",
        ),
        migrations.RenameField(
            model_name="usersecrets", old_name="api_key", new_name="value",
        ),
    ]
