# Generated by Django 4.1.3 on 2023-07-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_rename_api_name_usersecrets_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersecrets", old_name="user_id", new_name="user",
        ),
    ]
