# Generated by Django 4.1.13 on 2025-03-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_quota_mediacloud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quota_mediacloud_legacy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quota_reddit_pushshift',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quota_twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quota_youtube',
        ),
    ]
