# Generated by Django 4.1.3 on 2023-07-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_rename_user_id_usersecrets_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersecrets",
            name="key",
            field=models.CharField(
                choices=[
                    ("twitter-token", "Twitter Token"),
                    ("youtube-token", "Youtube Token"),
                    ("reddit-token", "Reddit Token"),
                ],
                max_length=150,
            ),
        ),
    ]
