# Generated by Django 4.1.13 on 2026-01-23 22:11
# phil cribbed this from https://github.com/cookiecutter/cookiecutter-django/issues/2851

from django.db import migrations


def create_system_task_user(apps, schema_editor):
    """
    create user to own background tasks like
    """
    from django.contrib.auth import get_user_model
    from django.conf import settings

    task_user = get_user_model().objects.create_user(
        username=settings.SYSTEM_TASK_USERNAME
    )
    task_user.set_unusable_password()
    task_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_resetcodes'),
    ]

    operations = [
        migrations.RunPython(create_system_task_user),
    ]
