# Generated by Django 4.1.6 on 2026-01-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_resetcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_email',
            field=models.BooleanField(default=True),
        ),
    ]
