# Generated by Django 4.1.3 on 2023-07-20 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0018_rename_usersecret_usersecrets"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserSecrets", new_name="UserSecret",),
    ]
