# Generated by Django 4.1.13 on 2026-08-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_create_system_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quota_mediacloud',
            field=models.IntegerField(default=None, null=True, blank=True),
        ),
        migrations.RunSQL(
            # forward migration:
            "UPDATE users_profile set quota_mediacloud = NULL where quota_mediacloud = 4000;",
            # reverse migration:
            "UPDATE users_profile set quota_mediacloud = 4000 where quota_mediacloud = NULL;",
        )
    ]
