# Generated by Django 4.1.13 on 2026-08-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_quota_mediacloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quota_mediacloud',
            field=models.IntegerField(blank=True, default=None, help_text='Empty for default quota', null=True),
        ),
    ]
