# Generated by Django 4.1.3 on 2023-07-20 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0019_rename_usersecrets_usersecret"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserSecret", new_name="UserSecrets",),
    ]
