# Generated by Django 4.1.3 on 2023-07-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_rename_usersecret_usersecrets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersecrets",
            name="key",
            field=models.TextField(
                choices=[
                    ("twitter-token", "Twitter Token"),
                    ("youtube-token", "Youtube Token"),
                    ("reddit-token", "Reddit Token"),
                ]
            ),
        ),
    ]
